# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irs4bOaTv_o6TlUPbjjtxixwJrr1hVI_
"""

import requests
import json
import os
import time
from datetime import datetime

# Task 1: Fetch Data from API - TrendPulse
# This script fetches top stories from HackerNews, categorizes them, and saves them into a structured JSON file for further processing.

def fetch_trendpulse_data():

    # API Endpoints
    TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
    ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

    headers = {"User-Agent": "TrendPulse/1.0"}

    # Define categories and their respective keywords for matching

    categories = {
        "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
        "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
        "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
        "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
        "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
    }

    all_collected_stories = []
    category_counts = {cat: 0 for cat in categories}
    max_per_category = 25

    try:
        # Step 1: Get the list of top 500 story IDs
        response = requests.get(TOP_STORIES_URL, headers=headers)
        response.raise_for_status()
        story_ids = response.json()[:500]
    except Exception as e:
        print(f"Failed to fetch top stories: {e}")
        return

    print("Starting data collection...")

    # Step 2: Loop through categories to fetch and filter stories
    for category, keywords in categories.items():
        print(f"Processing category: {category}...")

        for story_id in story_ids:
            # Stop if we have enough stories for this category
            if category_counts[category] >= max_per_category:
                break

            try:
                # Fetch individual story details
                item_res = requests.get(ITEM_URL.format(story_id), headers=headers)
                item_res.raise_for_status()
                story = item_res.json()

                # Skip if story is deleted or doesn't have a title
                if not story or 'title' not in story:
                    continue

                title = story.get('title', '')
                title_lower = title.lower()

                # Check if any keyword matches the title (case-insensitive)
                if any(kw.lower() in title_lower for kw in keywords):
                    # Extract required fields
                    story_data = {
                        "post_id": story.get("id"),
                        "title": title,
                        "category": category,
                        "score": story.get("score", 0),
                        "num_comments": story.get("descendants", 0),
                        "author": story.get("by", "unknown"),
                        "collected_at": datetime.now().isoformat()
                    }

                    all_collected_stories.append(story_data)
                    category_counts[category] += 1

            except Exception:
                # If a single request fails, print and move on per requirements
                print(f"Skipping story ID {story_id} due to fetch error.")
                continue

        # Wait 2 seconds between each category loop
        time.sleep(2)

    # Step 3: Save to JSON file
    if not os.path.exists('data'):
        os.makedirs('data')

    timestamp = datetime.now().strftime("%Y%m%d")
    filename = f"data/trends_{timestamp}.json"

    with open(filename, 'w') as f:
        json.dump(all_collected_stories, f, indent=4)

    print(f"\nSuccess! Collected a total of {len(all_collected_stories)} stories.")
    for cat, count in category_counts.items():
        print(f"- {cat}: {count}")
    print(f"Data saved to {filename}")

if __name__ == "__main__":
    fetch_trendpulse_data()

import pandas as pd
import glob
import os

# Task 2: Clean the Data & Save as CSV - TrendPulse
# This script processes the raw JSON data from Task 1 using Pandas,
# cleaning up duplicates, missing values, and low-quality entries.

def process_trendpulse_data():
    # Step 1: Load the JSON File
    # We look for the most recent trends file in the data/ directory
    try:
        json_files = glob.glob('data/trends_*.json')
        if not json_files:
            print("Error: No JSON data files found in data/ folder.")
            return

        # Sort to get the latest file if multiple exist
        latest_file = sorted(json_files)[-1]
        df = pd.read_json(latest_file)

        initial_count = len(df)
        print(f"Successfully loaded {initial_count} rows from {latest_file}.")

    except Exception as e:
        print(f"An error occurred while loading data: {e}")
        return

    # Step 2: Clean the Data
    # 2.1: Remove duplicates based on the unique post_id
    df = df.drop_duplicates(subset=['post_id'])

    # 2.2: Drop rows where critical identifying info or the score is missing
    df = df.dropna(subset=['post_id', 'title', 'score'])

    # 2.3: Ensure correct data types (HackerNews scores/comments should be integers)
    # fillna(0) handles cases where num_comments might be NaN before conversion
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].fillna(0).astype(int)

    # 2.4: Remove low quality stories (score < 5)
    df = df[df['score'] >= 5]

    # 2.5: Clean up whitespace in titles for a professional look
    df['title'] = df['title'].str.strip()

    final_count = len(df)
    print(f"Data cleaning complete. {final_count} rows remaining (Removed {initial_count - final_count} rows).")

    # Step 3: Save as CSV
    output_path = 'data/trends_clean.csv'
    try:
        # Save without the index column to keep the CSV tidy
        df.to_csv(output_path, index=False)
        print(f"Cleaned data saved to {output_path}.")

        # Summary statistics per category
        print("\n--- Summary by Category ---")
        category_summary = df['category'].value_counts()
        print(category_summary.to_string())

    except Exception as e:
        print(f"Error saving CSV: {e}")

if __name__ == "__main__":
    process_trendpulse_data()