# -*- coding: utf-8 -*-
"""task4_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irs4bOaTv_o6TlUPbjjtxixwJrr1hVI_
"""

import requests
import json
import os
import time
from datetime import datetime

# Task 1: Fetch Data from API - TrendPulse
# This script fetches top stories from HackerNews, categorizes them, and saves them into a structured JSON file for further processing.

def fetch_trendpulse_data():

    # API Endpoints
    TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
    ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

    headers = {"User-Agent": "TrendPulse/1.0"}

    # Define categories and their respective keywords for matching

    categories = {
        "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
        "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
        "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
        "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
        "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
    }

    all_collected_stories = []
    category_counts = {cat: 0 for cat in categories}
    max_per_category = 25

    try:
        # Step 1: Get the list of top 500 story IDs
        response = requests.get(TOP_STORIES_URL, headers=headers)
        response.raise_for_status()
        story_ids = response.json()[:500]
    except Exception as e:
        print(f"Failed to fetch top stories: {e}")
        return

    print("Starting data collection...")

    # Step 2: Loop through categories to fetch and filter stories
    for category, keywords in categories.items():
        print(f"Processing category: {category}...")

        for story_id in story_ids:
            # Stop if we have enough stories for this category
            if category_counts[category] >= max_per_category:
                break

            try:
                # Fetch individual story details
                item_res = requests.get(ITEM_URL.format(story_id), headers=headers)
                item_res.raise_for_status()
                story = item_res.json()

                # Skip if story is deleted or doesn't have a title
                if not story or 'title' not in story:
                    continue

                title = story.get('title', '')
                title_lower = title.lower()

                # Check if any keyword matches the title (case-insensitive)
                if any(kw.lower() in title_lower for kw in keywords):
                    # Extract required fields
                    story_data = {
                        "post_id": story.get("id"),
                        "title": title,
                        "category": category,
                        "score": story.get("score", 0),
                        "num_comments": story.get("descendants", 0),
                        "author": story.get("by", "unknown"),
                        "collected_at": datetime.now().isoformat()
                    }

                    all_collected_stories.append(story_data)
                    category_counts[category] += 1

            except Exception:
                # If a single request fails, print and move on per requirements
                print(f"Skipping story ID {story_id} due to fetch error.")
                continue

        # Wait 2 seconds between each category loop
        time.sleep(2)

    # Step 3: Save to JSON file
    if not os.path.exists('data'):
        os.makedirs('data')

    timestamp = datetime.now().strftime("%Y%m%d")
    filename = f"data/trends_{timestamp}.json"

    with open(filename, 'w') as f:
        json.dump(all_collected_stories, f, indent=4)

    print(f"\nSuccess! Collected a total of {len(all_collected_stories)} stories.")
    for cat, count in category_counts.items():
        print(f"- {cat}: {count}")
    print(f"Data saved to {filename}")

if __name__ == "__main__":
    fetch_trendpulse_data()

import pandas as pd
import glob
import os

# Task 2: Clean the Data & Save as CSV - TrendPulse
# This script processes the raw JSON data from Task 1 using Pandas,
# cleaning up duplicates, missing values, and low-quality entries.

def process_trendpulse_data():
    # Step 1: Load the JSON File
    # We look for the most recent trends file in the data/ directory
    try:
        json_files = glob.glob('data/trends_*.json')
        if not json_files:
            print("Error: No JSON data files found in data/ folder.")
            return

        # Sort to get the latest file if multiple exist
        latest_file = sorted(json_files)[-1]
        df = pd.read_json(latest_file)

        initial_count = len(df)
        print(f"Successfully loaded {initial_count} rows from {latest_file}.")

    except Exception as e:
        print(f"An error occurred while loading data: {e}")
        return

    # Step 2: Clean the Data
    # 2.1: Remove duplicates based on the unique post_id
    df = df.drop_duplicates(subset=['post_id'])

    # 2.2: Drop rows where critical identifying info or the score is missing
    df = df.dropna(subset=['post_id', 'title', 'score'])

    # 2.3: Ensure correct data types (HackerNews scores/comments should be integers)
    # fillna(0) handles cases where num_comments might be NaN before conversion
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].fillna(0).astype(int)

    # 2.4: Remove low quality stories (score < 5)
    df = df[df['score'] >= 5]

    # 2.5: Clean up whitespace in titles for a professional look
    df['title'] = df['title'].str.strip()

    final_count = len(df)
    print(f"Data cleaning complete. {final_count} rows remaining (Removed {initial_count - final_count} rows).")

    # Step 3: Save as CSV
    output_path = 'data/trends_clean.csv'
    try:
        # Save without the index column to keep the CSV tidy
        df.to_csv(output_path, index=False)
        print(f"Cleaned data saved to {output_path}.")

        # Summary statistics per category
        print("\n--- Summary by Category ---")
        category_summary = df['category'].value_counts()
        print(category_summary.to_string())

    except Exception as e:
        print(f"Error saving CSV: {e}")

if __name__ == "__main__":
    process_trendpulse_data()

import pandas as pd
import numpy as np

# Task 3: Analysis with Pandas & NumPy - TrendPulse
# This script loads the cleaned CSV from Task 2, performs statistical
# analysis using NumPy, and adds new calculated metrics for deeper insights.

def analyze_trendpulse_data():
    file_path = 'data/trends_clean.csv'

    # --- 1. Load and Explore ---
    try:
        df = pd.read_csv(file_path)

        print("--- Data Overview ---")
        print(f"First 5 rows:\n{df.head()}\n")
        print(f"DataFrame Shape: {df.shape} (Rows, Columns)")

        avg_score = df['score'].mean()
        avg_comments = df['num_comments'].mean()

        print(f"Average Score: {avg_score:.2f}")
        print(f"Average Comments: {avg_comments:.2f}\n")

    except FileNotFoundError:
        print(f"Error: {file_path} not found. Please run Task 2 first.")
        return

    # --- 2. Basic Analysis with NumPy ---
    # Converting pandas series to numpy arrays for specific calculations
    scores = df['score'].to_numpy()
    comments = df['num_comments'].to_numpy()

    print("--- NumPy Statistics (Scores) ---")
    print(f"Mean Score: {np.mean(scores):.2f}")
    print(f"Median Score: {np.median(scores)}")
    print(f"Std Deviation: {np.std(scores):.2f}")
    print(f"Highest Score: {np.max(scores)}")
    print(f"Lowest Score: {np.min(scores)}\n")

    # Find category with most stories
    top_category = df['category'].value_counts().idxmax()
    print(f"Category with most stories: {top_category}")

    # Find the story with the most comments
    max_comments_idx = np.argmax(comments)
    most_discussed_title = df.iloc[max_comments_idx]['title']
    most_discussed_count = df.iloc[max_comments_idx]['num_comments']
    print(f"Most discussed story: '{most_discussed_title}' with {most_discussed_count} comments.\n")

    # --- 3. Add New Columns ---
    # engagement: how much discussion per upvote (adding 1 to prevent division by zero)
    df['engagement'] = df['num_comments'] / (df['score'] + 1)

    # is_popular: Boolean flag based on the average score
    df['is_popular'] = df['score'] > avg_score

    # --- 4. Save the Result ---
    output_path = 'data/trends_analysed.csv'
    try:
        df.to_csv(output_path, index=False)
        print(f"Success! Analysis complete. Data saved to {output_path}.")
        print(f"Columns added: 'engagement' and 'is_popular'.")
    except Exception as e:
        print(f"Error saving analyzed data: {e}")

if __name__ == "__main__":
    analyze_trendpulse_data()

import pandas as pd
import matplotlib.pyplot as plt
import os

# Task 4: Visualizations - TrendPulse Dashboard
# This script loads the analyzed data and generates visual insights
# using Matplotlib to represent stories, categories, and engagement.

def generate_trendpulse_visuals():
    # --- 1. Setup ---
    file_path = 'data/trends_analysed.csv'
    output_dir = 'outputs'

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print("Error: data/trends_analysed.csv not found. Run Task 3 first.")
        return

    # Helper function to shorten titles for cleaner charts
    def shorten_title(t):
        return t[:47] + "..." if len(t) > 50 else t

    # --- 2. Chart 1: Top 10 Stories by Score ---
    top_10 = df.nlargest(10, 'score').copy()
    top_10['short_title'] = top_10['title'].apply(shorten_title)

    plt.figure(figsize=(10, 6))
    plt.barh(top_10['short_title'], top_10['score'], color='skyblue')
    plt.xlabel('Upvote Score')
    plt.title('Top 10 Most Popular Stories by Score')
    plt.gca().invert_yaxis()  # Highest score at the top
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart1_top_stories.png')
    plt.close()

    # --- 3. Chart 2: Stories per Category ---
    cat_counts = df['category'].value_counts()
    colors = ['gold', 'lightcoral', 'lightgreen', 'mediumpurple', 'lightskyblue']

    plt.figure(figsize=(8, 6))
    cat_counts.plot(kind='bar', color=colors[:len(cat_counts)])
    plt.title('Distribution of Stories per Category')
    plt.xlabel('Category')
    plt.ylabel('Number of Stories')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart2_categories.png')
    plt.close()

    # --- 4. Chart 3: Score vs Comments ---
    plt.figure(figsize=(8, 6))
    popular = df[df['is_popular'] == True]
    not_popular = df[df['is_popular'] == False]

    plt.scatter(not_popular['score'], not_popular['num_comments'], alpha=0.6, label='Normal', c='gray')
    plt.scatter(popular['score'], popular['num_comments'], alpha=0.8, label='Popular', c='orange', edgecolors='red')

    plt.title('Relationship: Score vs. Comments')
    plt.xlabel('Score')
    plt.ylabel('Number of Comments')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart3_scatter.png')
    plt.close()

    # --- Bonus: Combined Dashboard ---
    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle('TrendPulse Data Dashboard', fontsize=20, fontweight='bold')

    # Subplot 1: Top Stories
    axes[0].barh(top_10['short_title'], top_10['score'], color='skyblue')
    axes[0].set_title('Top 10 Stories')
    axes[0].invert_yaxis()

    # Subplot 2: Categories
    axes[1].bar(cat_counts.index, cat_counts.values, color=colors[:len(cat_counts)])
    axes[1].set_title('Stories per Category')
    axes[1].tick_params(axis='x', labelrotation=45)

    # Subplot 3: Scatter
    axes[2].scatter(not_popular['score'], not_popular['num_comments'], alpha=0.5, c='gray')
    axes[2].scatter(popular['score'], popular['num_comments'], alpha=0.7, c='orange')
    axes[2].set_title('Score vs Comments')
    axes[2].set_xlabel('Score')
    axes[2].set_ylabel('Comments')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(f'{output_dir}/dashboard.png')
    plt.show()

    print(f"Visualizations successfully saved in the '{output_dir}/' folder.")

if __name__ == "__main__":
    generate_trendpulse_visuals()