# -*- coding: utf-8 -*-
"""task2_data_processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dmv2585oQEorilGcMVf5Q55o5sJ87w8-
"""

import pandas as pd
import glob
import os

# Task 2: Clean the Data & Save as CSV - TrendPulse
# This script processes the raw JSON data from Task 1 using Pandas,
# cleaning up duplicates, missing values, and low-quality entries.

def process_trendpulse_data():
    # Step 1: Load the JSON File
    # We look for the most recent trends file in the data/ directory
    try:
        json_files = glob.glob('data/trends_*.json')
        if not json_files:
            print("Error: No JSON data files found in data/ folder.")
            return

        # Sort to get the latest file if multiple exist
        latest_file = sorted(json_files)[-1]
        df = pd.read_json(latest_file)

        initial_count = len(df)
        print(f"Successfully loaded {initial_count} rows from {latest_file}.")

    except Exception as e:
        print(f"An error occurred while loading data: {e}")
        return

    # Step 2: Clean the Data
    # 2.1: Remove duplicates based on the unique post_id
    df = df.drop_duplicates(subset=['post_id'])

    # 2.2: Drop rows where critical identifying info or the score is missing
    df = df.dropna(subset=['post_id', 'title', 'score'])

    # 2.3: Ensure correct data types (HackerNews scores/comments should be integers)
    # fillna(0) handles cases where num_comments might be NaN before conversion
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].fillna(0).astype(int)

    # 2.4: Remove low quality stories (score < 5)
    df = df[df['score'] >= 5]

    # 2.5: Clean up whitespace in titles for a professional look
    df['title'] = df['title'].str.strip()

    final_count = len(df)
    print(f"Data cleaning complete. {final_count} rows remaining (Removed {initial_count - final_count} rows).")

    # Step 3: Save as CSV
    output_path = 'data/trends_clean.csv'
    try:
        # Save without the index column to keep the CSV tidy
        df.to_csv(output_path, index=False)
        print(f"Cleaned data saved to {output_path}.")

        # Summary statistics per category
        print("\n--- Summary by Category ---")
        category_summary = df['category'].value_counts()
        print(category_summary.to_string())

    except Exception as e:
        print(f"Error saving CSV: {e}")

if __name__ == "__main__":
    process_trendpulse_data()